# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ObjCAFNetworkingCodeGenerator' do
  pod "AFNetworking", "~> 2.0"
  pod "AFNetworkActivityLogger", "~> 2.0"
end

