language: objective-c
node_js:
- '0.10'
before_install:
- npm install coffee-script
install:
- pod install --project-directory=./test/
- npm install
before_script:
- ./node_modules/.bin/cake archive
script:
- ./node_modules/.bin/cake test
deploy:
  provider: releases
  api_key:
    secure: ZVwjUUbF+Q+netNasYd2wH8jwoSiFQ0RdCAXJDI19flyaEajYvULNm+KpLHo9U0lRWmoNK/sWrvshd+v5qI2nN/NJr/XtzeXo3FMUHDOaPszsmcN/caup+G69gfDzbbg2y+DJSoSVw93Km31kPt6JgTub2bIRPNsBqyxYuo8QQ8=
  file: build/ObjCAFNetworkingCodeGenerator.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-ObjCAFNetworkingCodeGenerator
os:
  - osx
